import type { Metadata } from "next";
import { Poppins } from "next/font/google"; // Import Poppins
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "../components/layout/app-sidebar";
import { AppMobileMenu } from "../components/layout/app-mobile-menu";
import AppHeader from "@/components/layout/app-header";
import AppFooter from "@/components/layout/app-footer";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // Use the Poppins font variable here
        className={`${poppins.variable} antialiased`}
      >
        <SidebarProvider>
          <AppSidebar />
          <main className="w-full">
            <AppHeader />
            {children}
            <AppFooter />
          </main>
          <AppMobileMenu />
        </SidebarProvider>
      </body>
    </html>
  );
}
